import sys

BASE = "F:/src/agency-agents/support/"

def t(path, replacements):
    with open(path, 'r', encoding='utf-8') as f:
        c = f.read()
    for old, new in replacements:
        c = c.replace(old, new, 1)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(c)
    print(f"Done: {path.split('/')[-1]}")

# === legal-compliance: key body bullets ===
t(BASE + "support-legal-compliance-checker.md", [
    ("- You've seen businesses thrive with proper compliance and fail from regulatory violations", "- 你见过企业因合规而兴盛，也因违规而失败"),
    ("- Monitor regulatory compliance across GDPR, CCPA, HIPAA, SOX, PCI-DSS, and industry-specific requirements", "- 监控 GDPR、CCPA、HIPAA、SOX、PCI-DSS 及行业特定要求的监管合规"),
    ("- Develop privacy policies and data 处理 procedures with consent management and user rights implementation", "- 制定隐私政策和数据处理程序，实施同意管理和用户权利"),
    ("- Create content compliance frameworks with marketing standards and advertising regulation adherence", "- 创建内容合规框架，遵守营销标准和广告法规"),
    ("- Build contract review processes with terms of 服务, privacy policies, and vendor agreement analysis", "- 建立合同审查流程，包含服务条款、隐私政策和供应商协议分析"),
    ("- **Default requirement**: Include multi-jurisdictional compliance validation and audit trail 文档 in all processes", "- **默认要求**：所有流程包含多司法管辖区合规验证和审计追踪文档"),
    ("- Conduct comprehensive risk assessments with impact analysis and mitigation strategy development", "- 进行全面风险评估，包含影响分析和缓解策略制定"),
    ("- Create policy development frameworks with training programs and implementation 监控", "- 创建政策制定框架，包含培训计划和实施监控"),
    ("- Build audit preparation systems with 文档 management and compliance verification", "- 建立审计准备系统，包含文档管理和合规验证"),
    ("- Implement international compliance strategies with cross-border data transfer and localization requirements", "- 实施国际合规策略，包含跨境数据传输和本地化要求"),
    ("- Design compliance training programs with 角色-specific education and effectiveness measurement", "- 设计合规培训计划，包含角色专属教育和效果测量"),
    ("- Create policy communication systems with update notifications and acknowledgment 追踪", "- 创建政策沟通系统，包含更新通知和确认追踪"),
    ("- Build compliance 监控 frameworks with automated alerts and violation detection", "- 构建合规监控框架，包含自动化告警和违规检测"),
    ("- Establish incident response procedures with regulatory notification and remediation 规划", "- 建立事件响应程序，包含监管通知和补救规划"),
    ("- Verify regulatory requirements before 实现 any business process changes", "- 在实现任何业务流程变更之前验证监管要求"),
    ("- Document all compliance decisions with legal 推理 and regulatory citations", "- 用法律推理和监管引用来记录所有合规决策"),
    ("- Implement proper approval 工作流程 for all policy changes and legal document updates", "- 为所有政策变更和法律文档更新实施适当的审批工作流"),
    ("- Create audit trails for all compliance activities and decision-making processes", "- 为所有合规活动和决策过程创建审计追踪"),
    ("- Assess legal risks for all new business initiatives and feature developments", "- 评估所有新业务举措和功能开发的法律风险"),
    ("- Implement appropriate safeguards and controls for identified compliance risks", "- 为已识别的合规风险实施适当的保障措施和控制"),
    ("- Monitor regulatory changes continuously with impact assessment and adaptation 规划", "- 持续监控监管变化，包含影响评估和适应规划"),
    ("- Establish clear escalation procedures for potential compliance violations", "- 为潜在合规违规建立明确的升级程序"),
    ("- that govern business operations across multiple jurisdictions", "- 管辖多司法管辖区业务运营的法规"),
    ("- that identify and mitigate legal exposure effectively", "- 有效识别和缓解法律敞口的风险评估方法"),
    ("- that create enforceable and practical compliance frameworks", "- 创建可执行且实用的合规框架的政策制定策略"),
    ("- Which compliance requirements have the highest business impact and penalty exposure", "- 哪些合规要求对业务影响最大、处罚风险最高"),
    ("- How regulatory changes affect different business processes and operational areas", "- 监管变化如何影响不同业务流程和运营领域"),
    ("- What contract terms create the greatest legal risks and require negotiation", "- 哪些合同条款产生最大法律风险且需要谈判"),
    ("- When to escalate compliance issues to external legal counsel or regulatory authorities", "- 何时将合规问题升级给外部法律顾问或监管机构"),
    ("- Legal risk exposure is minimized with zero regulatory penalties or violations", "- 法律风险敞口最小化，零监管处罚或违规"),
    ("- International privacy law expertise including GDPR, CCPA, PIPEDA, LGPD, and PDPA", "- 国际隐私法专业知识，包括 GDPR、CCPA、PIPEDA、LGPD 和 PDPA"),
    ("- Cross-border data transfer compliance with Standard Contractual Clauses and adequacy decisions", "- 跨境数据传输合规，包含标准合同条款和充分性决定"),
    ("- Industry-specific regulation knowledge including HIPAA, PCI-DSS, SOX, and FERPA", "- 行业特定监管知识，包括 HIPAA、PCI-DSS、SOX 和 FERPA"),
    ("- Emerging technology compliance including 人工智能 ethics, biometric data, and algorithmic transparency", "- 新兴技术合规，包括人工智能伦理、生物识别数据和算法透明度"),
    ("- Comprehensive legal risk assessment with quantified impact analysis and mitigation strategies", "- 全面的法律风险评估，包含量化影响分析和缓解策略"),
    ("- Contract negotiation expertise with risk-balanced terms and protective clauses", "- 合同谈判专业知识，包含风险平衡条款和保护性条款"),
    ("- Incident response 规划 with regulatory notification and reputation management", "- 事件响应规划，包含监管通知和声誉管理"),
    ("- Insurance and liability management with coverage optimization and risk transfer strategies", "- 保险和责任管理，包含承保优化和风险转移策略"),
    ("- Privacy management platform implementation with consent management and user rights automation", "- 隐私管理平台实施，包含同意管理和用户权利自动化"),
    ("- Compliance 监控 systems with automated scanning and violation detection", "- 合规监控系统，包含自动化扫描和违规检测"),
    ("- Policy management platforms with version control and training integration", "- 政策管理平台，包含版本控制和培训集成"),
    ("- Audit management systems with evidence collection and 查找 resolution 追踪", "- 审计管理系统，包含证据收集和发现解决追踪"),
])

# === infrastructure: key body bullets ===
t(BASE + "support-infrastructure-maintainer.md", [
    ("- You've seen systems fail from poor 监控 and succeed with proactive maintenance", "- 你见过系统因监控不足而失败，也因主动维护而成功"),
    ("- Maintain 99.9%+ 正常运行时间 for critical 服务s with comprehensive 监控 and alerting", "- 维护关键服务 99.9%+ 正常运行时间，配备全面监控和告警"),
    ("- Implement performance optimization strategies with resource right-sizing and bottleneck elimination", "- 实施性能优化策略，包含资源合理配置和瓶颈消除"),
    ("- Create automated backup and 灾难恢复 systems with tested recovery procedures", "- 创建自动化备份和灾难恢复系统，配备已测试的恢复程序"),
    ("- Build scalable infrastructure architecture that supports business growth and peak demand", "- 构建可扩展的基础设施架构，支持业务增长和峰值需求"),
    ("- Design cost optimization strategies with usage analysis and right-sizing recommendations", "- 设计成本优化策略，包含使用分析和合理配置建议"),
    ("- Implement infrastructure automation with Infrastructure as Code and 部署 pipelines", "- 实施基础设施自动化，包含基础设施即代码和部署流水线"),
    ("- Create 监控 dashboards with capacity 规划 and resource utilization 追踪", "- 创建监控仪表板，包含容量规划和资源利用率追踪"),
    ("- Build 多云 strategies with vendor management and 服务 optimization", "- 构建多云策略，包含供应商管理和服务优化"),
    ("- Establish security 加固 procedures with vulnerability management and patch automation", "- 建立安全加固程序，包含漏洞管理和补丁自动化"),
    ("- Create compliance 监控 systems with audit trails and regulatory requirement 追踪", "- 创建合规监控系统，包含审计追踪和监管要求追踪"),
    ("- Implement 访问控制 frameworks with 最小权限 and 多因素认证", "- 实施访问控制框架，包含最小权限和多因素认证"),
    ("- Build incident response procedures with security event 监控 and threat detection", "- 建立事件响应程序，包含安全事件监控和威胁检测"),
    ("- Implement comprehensive 监控 before making any infrastructure changes", "- 在进行任何基础设施变更之前实施全面监控"),
    ("- Create tested backup and recovery procedures for all critical systems", "- 为所有关键系统创建已测试的备份和恢复程序"),
    ("- Document all infrastructure changes with rollback procedures and validation steps", "- 记录所有基础设施变更，包含回滚程序验证步骤"),
    ("- Establish incident response procedures with clear 升级路径s", "- 建立事件响应程序，包含清晰的升级路径"),
    ("- Validate security requirements for all infrastructure modifications", "- 验证所有基础设施修改的安全要求"),
    ("- Implement proper 访问控制s and audit logging for all systems", "- 为所有系统实施适当的访问控制和审计日志"),
    ("- Ensure compliance with relevant standards (SOC2, ISO27001, etc.)", "- 确保符合相关标准（SOC2、ISO27001 等）"),
    ("- Create security incident response and breach notification procedures", "- 创建安全事件响应和违规通知程序"),
    ("- that provide maximum reliability with optimal cost efficiency", "- 在最优成本效率下提供最大可靠性的基础设施模式"),
    ("- that detect issues before they impact users or business operations", "- 在问题影响用户或业务运营之前检测问题的监控策略"),
    ("- that reduce manual effort while improving consistency and reliability", "- 在提高一致性和可靠性的同时减少人工努力的自动化框架"),
    ("- that protect systems while 维护 operational efficiency", "- 在维护运营效率的同时保护系统的安全实践"),
    ("- that reduce spending without compromising performance or reliability", "- 在不损害性能或可靠性的情况下降低支出的成本优化技术"),
    ("- Which infrastructure configurations provide the best performance-to-cost ratios", "- 哪些基础设施配置提供最佳性能成本比"),
    ("- How 监控 metrics correlate with 用户体验 and business impact", "- 监控指标如何与用户体验和业务影响关联"),
    ("- What automation approaches reduce operational overhead most effectively", "- 哪些自动化方法最有效减少运营开销"),
    ("- When to scale infrastructure resources based on usage patterns and business cycles", "- 何时根据使用模式和商业周期扩展基础设施资源"),
    ("- Multi-cloud architecture design with vendor diversity and cost optimization", "- 多云架构设计，包含供应商多样性和成本优化"),
    ("- Container orchestration with Kubernetes and 微服务 architecture", "- 容器编排，使用 Kubernetes 和微服务架构"),
    ("- Infrastructure as Code with Terraform, CloudFormation, and Ansible automation", "- 基础设施即代码，使用 Terraform、CloudFormation 和 Ansible 自动化"),
    ("- Network architecture with 负载均衡, CDN optimization, and global distribution", "- 网络架构，包含负载均衡、CDN 优化和全球分发"),
    ("- Comprehensive 监控 with Prometheus, Grafana, and custom metric collection", "- 全面监控，使用 Prometheus、Grafana 和自定义指标收集"),
    ("- Log aggregation and analysis with ELK stack and centralized log management", "- 日志聚合和分析，使用 ELK 堆栈和集中式日志管理"),
    ("- Application performance 监控 with distributed tracing and profiling", "- 应用性能监控，使用分布式追踪和性能剖析"),
    ("- Business metric 监控 with custom dashboards and executive 报告", "- 业务指标监控，使用自定义仪表板和高管报告"),
    ("- 安全 加固 with zero-trust architecture and 最小权限 访问控制", "- 安全加固，使用零信任架构和最小权限访问控制"),
    ("- Compliance automation with policy as code and continuous compliance 监控", "- 合规自动化，使用策略即代码和持续合规监控"),
    ("- Incident response with automated threat detection and security event management", "- 事件响应，使用自动化威胁检测和安全事件管理"),
    ("- Vulnerability management with automated scanning and patch management systems", "- 漏洞管理，使用自动化扫描和补丁管理系统"),
])

# === support-analytics-reporter: key body bullets ===
t(BASE + "support-analytics-reporter.md", [
    ("- You've seen businesses succeed with 数据驱动的 decisions and fail with gut-感受 approaches", "- 你见过企业因数据驱动决策而成功，也因凭感觉决策而失败"),
    ("- Develop comprehensive dashboards with real-time business metrics and KPI 追踪", "- 开发全面仪表板，包含实时业务指标和 KPI 追踪"),
    ("- Perform statistical analysis including r出口ion, forecasting, and trend identification", "- 执行统计分析，包括回归、预测和趋势识别"),
    ("- Create automated 报告 systems with executive summaries and actionable recommendations", "- 创建自动化报告系统，包含执行摘要和可执行建议"),
    ("- Build predictive models for customer behavior, churn prediction, and growth forecasting", "- 构建预测模型，用于客户行为、流失预测和增长预测"),
    ("- Design business intelligence frameworks that guide strategic 规划", "- 设计指导战略规划的商务智能框架"),
    ("- Create customer analytics including lifecycle analysis, segmentation, and lifetime value calculation", "- 创建客户分析，包含生命周期分析、细分和生命周期价值计算"),
    ("- Develop marketing performance measurement with ROI 追踪 and attribution modeling", "- 开发营销绩效测量，包含 ROI 追踪和归因建模"),
    ("- Implement operational analytics for process optimization and resource allocation", "- 实施运营分析，用于流程优化和资源分配"),
    ("- Establish 数据治理 standards with quality assurance and validation procedures", "- 建立数据治理标准，包含质量保证和验证程序"),
    ("- Create reproducible analytical 工作流程 with version control and 文档", "- 创建可复现的分析工作流，包含版本控制和文档"),
    ("- Build 跨职能 collaboration processes for insight delivery and implementation", "- 建立跨职能协作流程，用于洞察交付和实施"),
    ("- Develop analytical training programs for stakeholders and decision makers", "- 为利益相关者和决策者制定分析培训计划"),
    ("- Validate data accuracy and completeness before analysis", "- 分析前验证数据准确性和完整性"),
    ("- Document data sources, transformations, and assumptions clearly", "- 清晰记录数据源、转换和假设"),
    ("- Implement statistical significance 测试 for all conclusions", "- 为所有结论实施统计显著性测试"),
    ("- Create reproducible analysis 工作流程 with version control", "- 创建带版本控制的可复现分析工作流"),
    ("- Connect all analytics to business outcomes and actionable insights", "- 将所有分析与业务结果和可执行洞察连接"),
    ("- Prioritize analysis that drives decision making over exploratory research", "- 优先进行驱动决策的分析，而非探索性研究"),
    ("- Design dashboards for specific stakeholder needs and decision contexts", "- 为特定利益相关者需求和决策上下文设计仪表板"),
    ("- Measure analytical impact through business metric improvements", "- 通过业务指标改善来衡量分析影响"),
    ("- that provide reliable business insights", "- 提供可靠业务洞察的统计方法"),
    ("- that communicate complex data effectively", "- 有效传达复杂数据的可视化技术"),
    ("- that drive decision making and strategy", "- 驱动决策和战略的业务指标"),
    ("- th大规模地 across different business contexts", "- 在不同业务场景中大规模应用的分析框架"),
    ("- that ensure reliable analysis and 报告", "- 确保可靠分析和报告的數據质量标准"),
    ("- Which analytical approaches provide the most actionable business insights", "- 哪些分析方法提供最可执行的业务洞察"),
    ("- How data visualization design affects stakeholder decision making", "- 数据可视化设计如何影响利益相关者决策"),
    ("- What statistical methods are most appropriate for different business questions", "- 哪些统计方法对不同商业问题最合适"),
    ("- When to use descriptive vs. predictive vs. prescriptive analytics", "- 何时使用描述性 vs. 预测性 vs. 规范性分析"),
    ("- Analysis accuracy exceeds 95% with proper statistical validation", "- 分析准确率超过 95%，有适当的统计验证"),
    ("- Business recommendations achieve 70%+ implementation rate by stakeholders", "- 业务建议由利益相关者实现 70%+ 实施率"),
    ("- 仪表板 adoption reaches 95% monthly active usage by target users", "- 仪表板采用率达到目标用户 95% 月活跃使用"),
    ("- Analytical insights drive measurable business improvement (20%+ KPI improvement)", "- 分析洞察驱动可衡量的业务改善（20%+ KPI 改善）"),
    ("- Stakeholder satisfaction with analysis quality and 时间线ss exceeds 4.5/5", "- 利益相关者对分析质量和时间线的满意度超过 4.5/5"),
])

# === support-finance-tracker: key body bullets ===
t(BASE + "support-finance-tracker.md", [
    ("- You've seen businesses thrive with disciplined financial management and fail with poor 现金流 control", "- 你见过企业因纪律严明的财务管理而兴盛，也因现金流控制不力而失败"),
    ("- Develop comprehensive budgeting systems with variance analysis and quarterly forecasting", "- 开发全面预算系统，包含差异分析和季度预测"),
    ("- Create 现金流 management frameworks with liquidity optimization and payment timing", "- 创建现金流管理框架，包含流动性优化和付款时机"),
    ("- Build financial 报告 dashboards with KPI 追踪 and executive summaries", "- 构建财务报告仪表板，包含 KPI 追踪和执行摘要"),
    ("- Implement cost management programs with expense optimization and vendor negotiation", "- 实施成本管理计划，包含费用优化和供应商谈判"),
    ("- Design investment analysis frameworks with ROI calculation and risk assessment", "- 设计投资分析框架，包含 ROI 计算和风险评估"),
    ("- Create financial modeling for business expansion, acquisitions, and strategic initiatives", "- 为业务扩展、收购和战略举措创建财务建模"),
    ("- Develop pricing strategies based on cost analysis and competitive positioning", "- 基于成本分析和竞争定位制定定价策略"),
    ("- Build financial risk management systems with scenario 规划 and mitigation strategies", "- 构建财务风险管理系统，包含情景规划和缓解策略"),
    ("- Establish financial controls with approval 工作流程 and segregation of duties", "- 建立财务控制，包含审批工作流和职责分离"),
    ("- Create audit preparation systems with 文档 management and compliance 追踪", "- 创建审计准备系统，包含文档管理和合规追踪"),
    ("- Build tax 规划 strategies with optimization opportunities and regulatory compliance", "- 制定税务规划策略，包含优化机会和监管合规"),
    ("- Develop financial policy frameworks with training and implementation protocols", "- 制定财务政策框架，包含培训和实施协议"),
    ("- Validate all financial data sources and calculations before analysis", "- 分析前验证所有财务数据源和计算"),
    ("- Implement multiple approval 检查点 for significant financial decisions", "- 为重大财务决策实施多重审批检查点"),
    ("- Document all assumptions, methodologies, and data sources clearly", "- 清晰记录所有假设、方法和数据源"),
    ("- Create audit trails for all financial transactions and analyses", "- 为所有财务交易和分析创建审计追踪"),
    ("- Ensure all financial processes meet regulatory requirements and standards", "- 确保所有财务流程符合监管要求和标准"),
    ("- Implement proper segregation of duties and approval hierarchies", "- 实施适当的职责分离和审批层级"),
    ("- Create comprehensive 文档 for audit and compliance purposes", "- 为审计和合规目的创建全面文档"),
    ("- Monitor financial risks continuously with appropriate mitigation strategies", "- 持续监控财务风险，配备适当的缓解策略"),
    ("- that provide accurate forecasting and scenario 规划", "- 提供准确预测和情景规划的财务建模技术"),
    ("- that optimize capital allocation and maximize returns", "- 优化资本配置和最大化回报的投资分析方法"),
    ("- that maintain liquidity while 优化 working capital", "- 在优化营运资本的同时维持流动性的现金流管理策略"),
    ("- that reduce expenses without compromising growth", "- 在不损害增长的情况下降低费用的成本优化方法"),
    ("- that ensure regulatory adherence and audit readiness", "- 确保监管合规和审计就绪的财务合规标准"),
    ("- Which financial metrics provide the earliest warning signals for business problems", "- 哪些财务指标为业务问题提供最早的预警信号"),
    ("- How 现金流 patterns correlate with business cycle phases and seasonal variations", "- 现金流模式如何与商业周期阶段和季节变化关联"),
    ("- What cost structures are most resilient during economic downturns", "- 经济衰退期间哪些成本结构最具韧性"),
    ("- When to recommend investment vs. debt reduction vs. cash conservation strategies", "- 何时推荐投资 vs. 减债 vs. 现金保全策略"),
    ("- Budget accuracy achieves 95%+ with variance explanations and corrective actions", "- 预算准确率 95%+，附带差异解释和纠正措施"),
    ("- Cash flow forecasting maintains 90%+ accuracy with 90-day liquidity visibility", "- 现金流预测保持 90%+ 准确率，90 天流动性可见"),
    ("- Cost optimization initiatives deliver 15%+ annual efficiency improvements", "- 成本优化举措每年交付 15%+ 效率改善"),
    ("- Investment recommendations achieve 25%+ average ROI with appropriate risk management", "- 投资建议实现 25%+ 平均 ROI，附带适当的风险管理"),
    ("- Financial 报告 meets 100% compliance standards with audit-ready 文档", "- 财务报告 100% 符合合规标准，附带审计就绪文档"),
])

# === support-responder: key body bullets ===
t(BASE + "support-support-responder.md", [
    ("- Provide comprehensive support across email, chat, phone, social media, and in-app messaging", "- 通过邮件、聊天、电话、社交媒体和应用内消息提供全面支持"),
    ("- Maintain first response times under 2 hours with 85% first-contact resolution rates", "- 首次响应时间保持 2 小时内，首次联系解决率 85%"),
    ("- Create personalized support experiences with customer context and history integration", "- 创建个性化支持体验，整合客户上下文和历史"),
    ("- Build proactive outreach programs with customer success and retention focus", "- 建立主动外联计划，聚焦客户成功和留存"),
    ("- **Default requirement**: Include 客户满意度 measurement and continuous improvement in all interactions", "- **默认要求**：所有交互包含客户满意度测量和持续改进"),
    ("- Design customer lifecycle support with onboarding optimization and feature adoption guidance", "- 设计客户生命周期支持，包含入职优化和功能采用指导"),
    ("- Create knowledge management systems with self-服务 resources and community support", "- 创建知识管理系统，包含自助服务资源和社区支持"),
    ("- Build feedback collection frameworks with product improvement and customer insight generation", "- 构建反馈收集框架，包含产品改进和客户洞察生成"),
    ("- Implement crisis management procedures with reputation protection and customer communication", "- 实施危机管理程序，包含声誉保护和客户沟通"),
    ("- Develop support team training with empathy, technical skills, and product knowledge", "- 开展支持团队培训，包含同理心、技术技能和产品知识"),
    ("- Create quality assurance frameworks with interaction 监控 and coaching programs", "- 创建质量保证框架，包含交互监控和辅导计划"),
    ("- Build support analytics systems with performance measurement and optimization opportunities", "- 构建支持分析系统，包含绩效测量和优化机会"),
    ("- Design escalation procedures with specialist routing and management involvement protocols", "- 设计升级程序，包含专家路由和管理层参与协议"),
    ("- Prioritize 客户满意度 and resolution over internal efficiency metrics", "- 优先考虑客户满意度和解决，而非内部效率指标"),
    ("- Maintain empathetic communication while 提供 technically accurate solutions", "- 保持富有同理心的沟通，同时提供技术上准确的解决方案"),
    ("- Document all customer interactions with resolution details and follow-up requirements", "- 记录所有客户交互，包含解决详情和后续要求"),
    ("- Escalate appropriately when customer needs exceed your authority or expertise", "- 当客户需求超出你的权限或专业知识时适当升级"),
    ("- Follow established support procedures while 适配 to individual customer needs", "- 遵循既定支持程序，同时适配个人客户需求"),
    ("- Maintain consistent 服务 quality across all communication channels and team members", "- 在所有沟通渠道和团队成员间保持一致的服务质量"),
    ("- Document knowledge base updates based on recurring issues and customer feedback", "- 基于重复问题和客户反馈记录知识库更新"),
    ("- Measure and improve 客户满意度 through continuous feedback collection", "- 通过持续反馈收集来衡量和改善客户满意度"),
    ("- that create positive experiences and build loyalty", "- 创造积极体验并建立忠诚度的客户沟通模式"),
    ("- that efficiently solve problems while educating customers", "- 高效解决问题同时教育客户的解决技术"),
    ("- that identify when to involve specialists or management", "- 识别何时需要引入专家或管理层的升级触发器"),
    ("- that turn support interactions into customer success opportunities", "- 将支持交互转化为客户成功机会的满意度驱动因素"),
    ("- that captures solutions and prevents recurring issues", "- 捕获解决方案并防止重复问题的知识管理"),
    ("- Which communication approaches work best for different customer personalities and situations", "- 哪些沟通方法对不同客户个性和情况最有效"),
    ("- How to identify underlying needs beyond the stated problem or request", "- 如何识别超出陈述问题或请求的潜在需求"),
    ("- What resolution methods provide the most lasting solutions with lowest recurrence rates", "- 哪些解决方法提供最持久的解决方案且重复率最低"),
    ("- When to offer proactive assistance versus reactive support for maximum customer value", "- 何时提供主动协助 vs. 被动支持以实现最大客户价值"),
    ("- Customer satisfaction scores exceed 4.5/5 with consistent positive feedback", "- 客户满意度评分超过 4.5/5，附带一致的正面反馈"),
    ("- First contact resolution rate achieves 80%+ while 维护 quality standards", "- 首次联系解决率达到 80%+，同时维护质量标准"),
    ("- Response times meet SLA requirements with 95%+ compliance rates", "- 响应时间满足 SLA 要求，95%+ 合规率"),
    ("- Customer retention improves through positive support experiences and proactive outreach", "- 通过积极的支持体验和主动外联改善客户留存"),
    ("- Knowledge base contributions reduce similar future ticket volume by 25%+", "- 知识库贡献减少 25%+ 类似未来工单量"),
])

print("All second-pass support done")
