#!/usr/bin/env python3
"""
Translate all agent definition directories to Chinese.
Handles: YAML frontmatter, section headers, bullet points, prose.
Preserves: code blocks, YAML keys, proper nouns, tool names.
"""
import os, re, sys

BASE = os.path.join(os.environ.get("WORKDIR", "F:\\src\\agency-agents"))

# ============================================================
# COMPREHENSIVE TRANSLATION DICTIONARIES
# ============================================================

# Header/Section title translations
HEADER_TRANS = {
    "Your Identity and Memory": "你的身份与记忆",
    "Your Core Mission": "你的核心使命",
    "Key Rules You Must Follow": "你必须遵守的关键规则",
    "Your Core Capabilities": "你的核心能力",
    "Your Workflow": "你的工作流程",
    "Your Communication Style": "你的沟通风格",
    "Your Success Metrics": "你的成功指标",
    "Advanced Capabilities": "高级能力",
    "Instructions Reference": "说明参考",
    "Identity & Memory": "身份与记忆",
    "Core Mission": "核心使命",
    "Must-Obey Rules": "必须遵守的规则",
    "Technical Deliverables": "技术交付物",
    "Workflow": "工作流程",
    "Communication Style": "沟通风格",
    "Success Metrics": "成功指标",
    "When to Bring In Other Agents": "何时引入其他代理",
    "Platform Expertise": "平台专业知识",
    "Your Core Belief": "你的核心信念",
    "Remediation Strategy": "修复策略",
    "Technical Stack": "技术栈",
    "Key Rules": "关键规则",
    "Rules You Must Follow": "你必须遵守的规则",
    "Critical Rules": "关键规则",
    "Rules of Engagement": "交战规则",
    "Your Identity": "你的身份",
    "Your Mission": "你的使命",
    "Your Capabilities": "你的能力",
    "Your Tools": "你的工具",
    "Your Process": "你的流程",
    "Your Principles": "你的原则",
    "Your Philosophy": "你的哲学",
    "Your Approach": "你的方法",
    "Your Mindset": "你的思维",
    "Your Ethos": "你的信念",
    "Your Values": "你的价值观",
    "Your Standards": "你的标准",
    "Your Expectations": "你的期望",
    "Your Boundaries": "你的边界",
    "Your Red Lines": "你的红线",
    "Your Non-negotiables": "你的不可协商事项",
    "Your Guardrails": "你的护栏",
    "Your Safety Checks": "你的安全检查",
    "Your Quality Bar": "你的质量标准",
    "Your Best Practices": "你的最佳实践",
    "Your Proven Patterns": "你的已验证模式",
    "Your Anti-patterns": "你的反模式",
    "Your Gotchas": "你的注意事项",
    "Your Pitfalls": "你的陷阱",
    "Your Lessons Learned": "你的经验教训",
    "Your War Stories": "你的实战故事",
    "Your Playbooks": "你的手册",
    "Your Runbooks": "你的操作手册",
    "Your SOPs": "你的标准操作程序",
    "Your Checklists": "你的检查清单",
    "Your Templates": "你的模板",
    "Your Examples": "你的示例",
    "Your Case Studies": "你的案例研究",
    "Your References": "你的参考资料",
    "Your Resources": "你的资源",
    "Your Learning Paths": "你的学习路径",
    "Your Growth Plan": "你的成长计划",
    "Your Career Path": "你的职业路径",
    "Your Skill Tree": "你的技能树",
    "Your Knowledge Base": "你的知识库",
    "Your Memory Bank": "你的记忆库",
    "Your Working Memory": "你的工作记忆",
    "Your Long-term Memory": "你的长期记忆",
    "Your Episodic Memory": "你的情景记忆",
    "Your Semantic Memory": "你的语义记忆",
    "Your Procedural Memory": "你的程序性记忆",
    "Your Working Context": "你的工作上下文",
    "Your Project Context": "你的项目上下文",
    "Your Team Context": "你的团队上下文",
    "Your Org Context": "你的组织上下文",
    "Your Domain Context": "你的领域上下文",
    "Your Business Context": "你的业务上下文",
    "Your Technical Context": "你的技术上下文",
    "Your Operational Context": "你的运维上下文",
    "Your Strategic Context": "你的战略上下文",
    "Your Tactical Context": "你的战术上下文",
    "Your Execution Context": "你的执行上下文",
    "Your Decision Context": "你的决策上下文",
    "Your Risk Context": "你的风险上下文",
    "Your Compliance Context": "你的合规上下文",
    "Your Security Context": "你的安全上下文",
    "Your Privacy Context": "你的隐私上下文",
    "Your Ethics Context": "你的伦理上下文",
    "Your Legal Context": "你的法律上下文",
    "Your Regulatory Context": "你的监管上下文",
    "Your Audit Context": "你的审计上下文",
    "Your Governance Context": "你的治理上下文",
    "Your Management Context": "你的管理上下文",
    "Your Leadership Context": "你的领导上下文",
    "Your Culture Context": "你的文化上下文",
    "Your Organization Context": "你的组织上下文",
    "Your Stakeholder Context": "你的利益相关者上下文",
    "Your Customer Context": "你的客户上下文",
    "Your User Context": "你的用户上下文",
    "Your Developer Context": "你的开发者上下文",
    "Your Designer Context": "你的设计上下文",
    "Your Product Context": "你的产品上下文",
    "Your Engineering Context": "你的工程上下文",
    "Your Architecture Context": "你的架构上下文",
    "Your Infrastructure Context": "你的基础设施上下文",
    "Your Operations Context": "你的运维上下文",
    "Your DevOps Context": "你的 DevOps 上下文",
    "Your SRE Context": "你的 SRE 上下文",
    "Your Platform Context": "你的平台上下文",
    "Your Cloud Context": "你的云上下文",
    "Step 1": "第一步",
    "Step 2": "第二步",
    "Step 3": "第三步",
    "Step 4": "第四步",
    "Step 5": "第五步",
    "Step 6": "第六步",
    "Step 7": "第七步",
    "Step 8": "第八步",
    "Step 9": "第九步",
    "Step 10": "第十步",
    "You succeed when": "你成功时",
    "When you succeed": "当你成功时",
    "You remember": "你记得",
    "Role": "角色",
    "Personality": "性格",
    "Memory": "记忆",
    "Experience": "经验",
    "Architecture": "架构",
    "Security": "安全",
    "Performance": "性能",
    "Quality": "质量",
    "Reliability": "可靠性",
    "Scalability": "可扩展性",
    "Availability": "可用性",
    "Monitoring": "监控",
    "Logging": "日志",
    "Testing": "测试",
    "Deployment": "部署",
    "Integration": "集成",
    "Automation": "自动化",
    "Observability": "可观测性",
    "Incident Management": "事件管理",
    "Change Management": "变更管理",
    "Release Management": "发布管理",
    "Risk Management": "风险管理",
    "Compliance": "合规性",
    "Governance": "治理",
    "Audit": "审计",
    "Backup": "备份",
    "Recovery": "恢复",
    "Disaster Recovery": "灾难恢复",
    "Business Continuity": "业务连续性",
    "High Availability": "高可用性",
    "Fault Tolerance": "容错",
    "Load Balancing": "负载均衡",
    "Auto-scaling": "自动扩缩容",
    "Health Checks": "健康检查",
    "Failover": "故障转移",
    "Error Handling": "错误处理",
    "Graceful Degradation": "优雅降级",
    "Circuit Breaker": "断路器",
    "Retry with Backoff": "带退避的重试",
    "Idempotency": "幂等性",
    "Timeout": "超时",
    "Rate Limiting": "速率限制",
    "Throttling": "节流",
    "Feature Flag": "特性标志",
    "A/B Testing": "A/B 测试",
    "Canary Deployment": "金丝雀部署",
    "Blue-green Deployment": "蓝绿部署",
    "Rolling Deployment": "滚动部署",
    "Rollback": "回滚",
    "Health Monitoring": "健康监控",
    "Performance Monitoring": "性能监控",
    "Security Monitoring": "安全监控",
    "Log Aggregation": "日志聚合",
    "Metrics Collection": "指标收集",
    "Trace Analysis": "追踪分析",
    "Alerting": "告警",
    "Dashboard": "仪表板",
    "Report": "报告",
    "User Experience": "用户体验",
    "Developer Experience": "开发者体验",
    "User Interface": "用户界面",
    "User Experience Design": "用户体验设计",
    "Information Architecture": "信息架构",
    "Interaction Design": "交互设计",
    "Visual Design": "视觉设计",
    "Accessibility": "无障碍",
    "Internationalization": "国际化",
    "Localization": "本地化",
    "Responsive Design": "响应式设计",
    "Cross-browser Compatibility": "跨浏览器兼容性",
    "Mobile-first": "移动端优先",
    "SEO Optimization": "SEO 优化",
    "Core Web Vitals": "核心 Web 指标",
    "Time to First Byte": "首字节时间",
    "First Contentful Paint": "首次内容渲染",
    "Largest Contentful Paint": "最大内容渲染",
    "Cumulative Layout Shift": "累积布局偏移",
    "Interaction to Next Paint": "交互到下一次渲染",
    "First Input Delay": "首次输入延迟",
    "Time to Interactive": "可交互时间",
    "Speed Index": "速度指数",
    "Total Blocking Time": "总阻塞时间",
    "Server-side Rendering": "服务端渲染",
    "Static Site Generation": "静态站点生成",
    "Progressive Web App": "渐进式 Web 应用",
    "Single Page Application": "单页应用",
    "Micro-frontends": "微前端",
    "Component Library": "组件库",
    "Design System": "设计系统",
    "Unit Testing": "单元测试",
    "Integration Testing": "集成测试",
    "End-to-End Testing": "端到端测试",
    "Component Testing": "组件测试",
    "Visual Regression Testing": "视觉回归测试",
    "Load Testing": "负载测试",
    "Stress Testing": "压力测试",
    "Security Testing": "安全测试",
    "Penetration Testing": "渗透测试",
    "Vulnerability Scanning": "漏洞扫描",
    "Static Analysis": "静态分析",
    "Dynamic Analysis": "动态分析",
    "Code Quality": "代码质量",
    "Technical Debt": "技术债务",
    "Code Smell": "代码异味",
    "Refactoring": "重构",
    "Design Patterns": "设计模式",
    "Clean Code": "整洁代码",
    "SOLID Principles": "SOLID 原则",
    "DRY Principle": "DRY 原则",
    "KISS Principle": "KISS 原则",
    "YAGNI Principle": "YAGNI 原则",
    "Single Responsibility": "单一职责",
    "Open/Closed": "开闭",
    "Liskov Substitution": "里氏替换",
    "Interface Segregation": "接口隔离",
    "Dependency Inversion": "依赖倒置",
    "Don't Repeat Yourself": "不要重复自己",
    "Keep It Simple, Stupid": "保持简单",
    "You Aren't Gonna Need It": "你不需要它",
    "Microservices": "微服务",
    "Monolith": "单体",
    "Service Mesh": "服务网格",
    "API Design": "API 设计",
    "RESTful API": "RESTful API",
    "GraphQL API": "GraphQL API",
    "gRPC API": "gRPC API",
    "Event-Driven Architecture": "事件驱动架构",
    "Event Sourcing": "事件溯源",
    "Domain-Driven Design": "领域驱动设计",
    "Serverless Architecture": "无服务器架构",
    "Microservices Architecture": "微服务架构",
    "Service-Oriented Architecture": "面向服务架构",
    "Layered Architecture": "分层架构",
    "Hexagonal Architecture": "六边形架构",
    "Clean Architecture": "整洁架构",
    "Onion Architecture": "洋葱架构",
    "Ports and Adapters": "端口和适配器",
    "Dependency Injection": "依赖注入",
    "Inversion of Control": "控制反转",
    "Aspect-Oriented Programming": "面向切面编程",
    "Functional Programming": "函数式编程",
    "Object-Oriented Programming": "面向对象编程",
    "Reactive Programming": "响应式编程",
    "Event-Driven Programming": "事件驱动编程",
    "Declarative Programming": "声明式编程",
    "Imperative Programming": "命令式编程",
    "Multi-threading": "多线程",
    "Async/Await": "异步/等待",
    "Callback": "回调",
    "Coroutine": "协程",
    "Actor Model": "Actor 模型",
    "Message Passing": "消息传递",
    "Shared Memory": "共享内存",
    "Lock-Free Programming": "无锁编程",
    "Reference Counting": "引用计数",
    "Garbage Collection": "垃圾回收",
    "Memory Management": "内存管理",
    "Memory Leaks": "内存泄漏",
    "Dangling Pointers": "悬挂指针",
    "Use-After-Free": "释放后使用",
    "Buffer Overflow": "缓冲区溢出",
    "Integer Overflow": "整数溢出",
    "Format String": "格式化字符串",
    "SQL Injection": "SQL 注入",
    "Cross-Site Scripting": "跨站脚本",
    "Cross-Site Request Forgery": "跨站请求伪造",
    "Server-Side Request Forgery": "服务端请求伪造",
    "Path Traversal": "路径遍历",
    "Command Injection": "命令注入",
    "Code Injection": "代码注入",
    "Eval Injection": "Eval 注入",
    "Template Injection": "模板注入",
    "XML External Entity": "XML 外部实体",
    "Denial of Service": "拒绝服务",
    "Distributed Denial of Service": "分布式拒绝服务",
    "Brute Force": "暴力破解",
    "Credential Stuffing": "凭证填充",
    "Password Spraying": "密码喷洒",
    "Phishing": "网络钓鱼",
    "Social Engineering": "社会工程",
    "Insider Threat": "内部威胁",
    "Supply Chain Attack": "供应链攻击",
    "Zero-Day": "零日漏洞",
    "Vulnerability": "漏洞",
    "Threat": "威胁",
    "Risk": "风险",
    "Exploit": "利用",
    "Payload": "载荷",
    "Attack Vector": "攻击向量",
    "Attack Surface": "攻击面",
    "Attack Path": "攻击路径",
    "Kill Chain": "杀伤链",
    "MITRE ATT&CK": "MITRE ATT&CK",
    "OWASP Top 10": "OWASP Top 10",
    "ISO 27001": "ISO 27001",
    "SOC 2": "SOC 2",
    "PCI DSS": "PCI DSS",
    "HIPAA": "HIPAA",
    "GDPR": "GDPR",
    "CCPA": "CCPA",
    "Infrastructure as Code": "基础设施即代码",
    "Secret Management": "密钥管理",
    "Certificate Management": "证书管理",
    "Event Bus": "事件总线",
    "Event Stream": "事件流",
    "Real-time Processing": "实时处理",
    "Batch Processing": "批量处理",
    "Stream Processing": "流处理",
    "Data Governance": "数据治理",
    "Data Security": "数据安全",
    "Data Privacy": "数据隐私",
    "Data Compliance": "数据合规",
    "DevOps": "DevOps",
    "Platform Engineering": "平台工程",
    "Site Reliability Engineering": "站点可靠性工程",
    "System Architecture": "系统架构",
    "Software Engineering": "软件工程",
    "Data Engineering": "数据工程",
    "ML Engineering": "ML 工程",
    "AI Engineering": "AI 工程",
    "Cybersecurity": "网络安全",
    "Cloud Engineering": "云工程",
    "Index Strategy": "索引策略",
    "Caching Strategy": "缓存策略",
    "Best Practices": "最佳实践",
    "System Design": "系统设计",
    "User Journey": "用户旅程",
    "Data Privacy": "数据隐私",
    "Load Testing": "负载测试",
    "Next Steps": "后续步骤",
    "Concrete Examples": "具体示例",
    "Output Format": "输出格式",
    "Industry Standards": "行业标准",
    "Mission-critical": "关键任务的",
    "Deliverable Templates": "交付物模板",
    "Database Architecture": "数据库架构",
    "Prioritization": "优先级排序",
    "Deep Expertise": "深厚专长",
    "Workflow Integration": "工作流程集成",
    "Throughout the Conversation": "整个对话中",
    "Remember and Build Upon": "记住并建立在以下基础上",
    "Remember and Accumulate Expertise": "记住并积累专业知识",
    "Battle-tested": "经过实战验证的",
    "Context Size": "上下文大小",
    "Context Window": "上下文窗口",
    "Context": "上下文",
    "Named Entity Recognition": "命名实体识别",
    "Retrieval-Augmented Generation": "检索增强生成",
    "Load Balancer": "负载均衡器",
    "Data-driven": "数据驱动的",
    "Uptime": "正常运行时间",
    "End-to-End Testing": "端到端测试",
    "Microservices Architecture": "微服务架构",
    "Event-driven": "事件驱动的",
    "Multi-factor Authentication": "多因素认证",
    "Screen Reader": "屏幕阅读器",
    "Computer Vision": "计算机视觉",
    "Database Optimization": "数据库优化",
    "Two-site Three-center": "两地三中心",
    "Same-city Dual-active": "同城双活",
    "Shadow Testing": "影子测试",
    "Post-mortem": "事后复盘",
    "Root Cause Analysis": "根因分析",
    "SM Algorithm": "国密算法",
    "Parameterized Query": "参数化查询",
    "WeChat Pay": "微信支付",
    "Regression Testing": "回归测试",
    "Defense in Depth": "纵深防御",
    "Horizontal Scaling": "水平扩展",
    "Mobile-first": "移动优先",
    "Visual Design": "视觉设计",
    "Model Serving": "模型服务",
    "Model Testing": "模型测试",
    "Knowledge Management": "知识管理",
    "Change Management": "变革管理",
}

# Word-level translations (sorted by length for longest-first matching)
WORD_TRANS = {
    "Machine Learning": "机器学习",
    "Natural Language Processing": "自然语言处理",
    "Computer Vision": "计算机视觉",
    "Reinforcement Learning": "强化学习",
    "Recommendation System": "推荐系统",
    "Knowledge Graph": "知识图谱",
    "Deep Learning": "深度学习",
    "Neural Network": "神经网络",
    "Generative": "生成式",
    "Diffusion Model": "扩散模型",
    "Multimodal": "多模态",
    "Speech Recognition": "语音识别",
    "Text Summarization": "文本摘要",
    "Sentiment Analysis": "情感分析",
    "Entity Extraction": "实体抽取",
    "Machine Translation": "机器翻译",
    "Embedding": "嵌入",
    "Vector Database": "向量数据库",
    "Prompt Engineering": "提示工程",
    "Fine-tuning": "微调",
    "Hyperparameter Tuning": "超参数调优",
    "Model Training": "模型训练",
    "Model Inference": "模型推理",
    "Model Deployment": "模型部署",
    "Model Monitoring": "模型监控",
    "Model Versioning": "模型版本",
    "Model Evaluation": "模型评估",
    "Model Validation": "模型验证",
    "Model Drift": "模型漂移",
    "Model Compression": "模型压缩",
    "Feature Engineering": "特征工程",
    "Data Pipeline": "数据管道",
    "Data Quality": "数据质量",
    "Data Warehouse": "数据仓库",
    "Data Lake": "数据湖",
    "Data Lakehouse": "数据湖仓",
    "Real-time": "实时",
    "Batch": "批量",
    "Streaming": "流式",
    "Edge Computing": "边缘计算",
    "Hybrid Deployment": "混合部署",
    "Production-Ready": "生产就绪",
    "Continuous Integration": "持续集成",
    "Continuous Deployment": "持续部署",
    "Continuous Delivery": "持续交付",
    "Version Control": "版本控制",
    "Code Review": "代码审查",
    "Static Analysis": "静态分析",
    "Automated Testing": "自动化测试",
    "Unit Testing": "单元测试",
    "Integration Testing": "集成测试",
    "End-to-End": "端到端",
    "Performance Testing": "性能测试",
    "Stress Testing": "压力测试",
    "Security Testing": "安全测试",
    "Penetration Testing": "渗透测试",
    "Accessibility Testing": "无障碍测试",
    "Keyboard Navigation": "键盘导航",
    "Semantic": "语义化",
    "Multilingual": "多语言",
    "Internationalization": "国际化",
    "Localization": "本地化",
    "Configuration Management": "配置管理",
    "Infrastructure": "基础设施",
    "Cloud Services": "云服务",
    "Server": "服务器",
    "Microservices": "微服务",
    "Containerization": "容器化",
    "Orchestration": "编排",
    "Load Balancing": "负载均衡",
    "Auto-scaling": "自动扩缩容",
    "Service Mesh": "服务网格",
    "Serverless": "无服务器",
    "Event-driven": "事件驱动",
    "Message Queue": "消息队列",
    "Distributed": "分布式",
    "Consistency": "一致性",
    "Availability": "可用性",
    "Partition Tolerance": "分区容忍",
    "Reliability": "可靠性",
    "Scalability": "可扩展性",
    "Performance Optimization": "性能优化",
    "Security Hardening": "安全加固",
    "Data Protection": "数据保护",
    "Privacy-preserving": "隐私保护",
    "Differential Privacy": "差分隐私",
    "Federated Learning": "联邦学习",
    "Adversarial": "对抗",
    "Explainability": "可解释性",
    "Model Explainability": "模型可解释性",
    "Transparency": "透明度",
    "Model Transparency": "模型透明度",
    "Fairness": "公平性",
    "Bias Detection": "偏见检测",
    "Fairness Metrics": "公平性指标",
    "Compliance": "合规性",
    "Version Management": "版本管理",
    "Rollback": "回滚",
    "Canary": "金丝雀",
    "Blue-green": "蓝绿",
    "Feature Flag": "特性标志",
    "Error Handling": "错误处理",
    "Graceful Degradation": "优雅降级",
    "Circuit Breaker": "断路器",
    "Retry": "重试",
    "Backoff": "退避",
    "Idempotency": "幂等性",
    "Rate Limiting": "速率限制",
    "Throttling": "节流",
    "Dead-letter Queue": "死信队列",
    "Circuit Breaking": "熔断",
    "Isolation": "隔离",
    "Timeout": "超时",
    "Caching": "缓存",
    "Object Storage": "对象存储",
    "Database Optimization": "数据库优化",
    "Index Optimization": "索引优化",
    "Query Optimization": "查询优化",
    "Database Migration": "数据库迁移",
    "Database Backup": "数据库备份",
    "Database Recovery": "数据库恢复",
    "Database Replication": "数据库复制",
    "Database Sharding": "数据库分片",
    "Database Partitioning": "数据库分区",
    "Transaction Management": "事务管理",
    "Concurrency Control": "并发控制",
    "Deadlock": "死锁",
    "Locking": "锁机制",
    "Connection Pool": "连接池",
    "Session Management": "会话管理",
    "Authentication": "认证",
    "Authorization": "授权",
    "Role": "角色",
    "Permission": "权限",
    "Access Control": "访问控制",
    "Multi-factor Authentication": "多因素认证",
    "Single Sign-on": "单点登录",
    "API Gateway": "API 网关",
    "Rate Limiting": "速率限制",
    "API Versioning": "API 版本",
    "API Documentation": "API 文档",
    "API Testing": "API 测试",
    "API Security": "API 安全",
    "REST API": "REST API",
    "GraphQL": "GraphQL",
    "gRPC": "gRPC",
    "WebSocket": "WebSocket",
    "Webhook": "Webhook",
    "SDK": "SDK",
    "CLI": "CLI",
    "GUI": "GUI",
    "API": "API",
    "Architecture": "架构",
    "Security": "安全",
    "Performance": "性能",
    "Quality": "质量",
    "Reliability": "可靠性",
    "Scalability": "可扩展性",
    "Availability": "可用性",
    "Monitoring": "监控",
    "Logging": "日志",
    "Deployment": "部署",
    "Integration": "集成",
    "Automation": "自动化",
    "Observability": "可观测性",
    "Incident Management": "事件管理",
    "Change Management": "变更管理",
    "Release Management": "发布管理",
    "Risk Management": "风险管理",
    "Governance": "治理",
    "Audit": "审计",
    "Backup": "备份",
    "Recovery": "恢复",
    "Disaster Recovery": "灾难恢复",
    "Business Continuity": "业务连续性",
    "High Availability": "高可用性",
    "Fault Tolerance": "容错",
    "Health Checks": "健康检查",
    "Failover": "故障转移",
    "User Experience": "用户体验",
    "Developer Experience": "开发者体验",
    "User Interface": "用户界面",
    "User Experience Design": "用户体验设计",
    "Information Architecture": "信息架构",
    "Interaction Design": "交互设计",
    "Visual Design": "视觉设计",
    "Accessibility": "无障碍",
    "Internationalization": "国际化",
    "Localization": "本地化",
    "Responsive Design": "响应式设计",
    "Cross-browser Compatibility": "跨浏览器兼容性",
    "Mobile-first": "移动端优先",
    "SEO Optimization": "SEO 优化",
    "Core Web Vitals": "核心 Web 指标",
    "Time to First Byte": "首字节时间",
    "First Contentful Paint": "首次内容渲染",
    "Largest Contentful Paint": "最大内容渲染",
    "Cumulative Layout Shift": "累积布局偏移",
    "Interaction to Next Paint": "交互到下一次渲染",
    "First Input Delay": "首次输入延迟",
    "Time to Interactive": "可交互时间",
    "Speed Index": "速度指数",
    "Total Blocking Time": "总阻塞时间",
    "Server-side Rendering": "服务端渲染",
    "Static Site Generation": "静态站点生成",
    "Progressive Web App": "渐进式 Web 应用",
    "Single Page Application": "单页应用",
    "Micro-frontends": "微前端",
    "Component Library": "组件库",
    "Design System": "设计系统",
    "Visual Regression Testing": "视觉回归测试",
    "Load Testing": "负载测试",
    "Stress Testing": "压力测试",
    "Security Testing": "安全测试",
    "Penetration Testing": "渗透测试",
    "Vulnerability Scanning": "漏洞扫描",
    "Static Analysis": "静态分析",
    "Dynamic Analysis": "动态分析",
    "Code Quality": "代码质量",
    "Technical Debt": "技术债务",
    "Code Smell": "代码异味",
    "Refactoring": "重构",
    "Design Patterns": "设计模式",
    "Clean Code": "整洁代码",
    "SOLID Principles": "SOLID 原则",
    "DRY Principle": "DRY 原则",
    "KISS Principle": "KISS 原则",
    "YAGNI Principle": "YAGNI 原则",
    "Single Responsibility": "单一职责",
    "Open/Closed": "开闭",
    "Liskov Substitution": "里氏替换",
    "Interface Segregation": "接口隔离",
    "Dependency Inversion": "依赖倒置",
    "Don't Repeat Yourself": "不要重复自己",
    "Keep It Simple, Stupid": "保持简单",
    "You Aren't Gonna Need It": "你不需要它",
    "Microservices": "微服务",
    "Monolith": "单体",
    "Service Mesh": "服务网格",
    "API Design": "API 设计",
    "RESTful API": "RESTful API",
    "GraphQL API": "GraphQL API",
    "gRPC API": "gRPC API",
    "Event-Driven Architecture": "事件驱动架构",
    "Event Sourcing": "事件溯源",
    "Domain-Driven Design": "领域驱动设计",
    "Serverless Architecture": "无服务器架构",
    "Microservices Architecture": "微服务架构",
    "Service-Oriented Architecture": "面向服务架构",
    "Layered Architecture": "分层架构",
    "Hexagonal Architecture": "六边形架构",
    "Clean Architecture": "整洁架构",
    "Onion Architecture": "洋葱架构",
    "Ports and Adapters": "端口和适配器",
    "Dependency Injection": "依赖注入",
    "Inversion of Control": "控制反转",
    "Aspect-Oriented Programming": "面向切面编程",
    "Functional Programming": "函数式编程",
    "Object-Oriented Programming": "面向对象编程",
    "Reactive Programming": "响应式编程",
    "Event-Driven Programming": "事件驱动编程",
    "Declarative Programming": "声明式编程",
    "Imperative Programming": "命令式编程",
    "Multi-threading": "多线程",
    "Async/Await": "异步/等待",
    "Callback": "回调",
    "Coroutine": "协程",
    "Actor Model": "Actor 模型",
    "Message Passing": "消息传递",
    "Shared Memory": "共享内存",
    "Lock-Free Programming": "无锁编程",
    "Reference Counting": "引用计数",
    "Garbage Collection": "垃圾回收",
    "Memory Management": "内存管理",
    "Memory Leaks": "内存泄漏",
    "Dangling Pointers": "悬挂指针",
    "Use-After-Free": "释放后使用",
    "Buffer Overflow": "缓冲区溢出",
    "Integer Overflow": "整数溢出",
    "Format String": "格式化字符串",
    "SQL Injection": "SQL 注入",
    "Cross-Site Scripting": "跨站脚本",
    "Cross-Site Request Forgery": "跨站请求伪造",
    "Server-Side Request Forgery": "服务端请求伪造",
    "Path Traversal": "路径遍历",
    "Command Injection": "命令注入",
    "Code Injection": "代码注入",
    "Eval Injection": "Eval 注入",
    "Template Injection": "模板注入",
    "XML External Entity": "XML 外部实体",
    "Denial of Service": "拒绝服务",
    "Distributed Denial of Service": "分布式拒绝服务",
    "Brute Force": "暴力破解",
    "Credential Stuffing": "凭证填充",
    "Password Spraying": "密码喷洒",
    "Phishing": "网络钓鱼",
    "Social Engineering": "社会工程",
    "Insider Threat": "内部威胁",
    "Supply Chain Attack": "供应链攻击",
    "Zero-Day": "零日漏洞",
    "Vulnerability": "漏洞",
    "Threat": "威胁",
    "Risk": "风险",
    "Exploit": "利用",
    "Payload": "载荷",
    "Attack Vector": "攻击向量",
    "Attack Surface": "攻击面",
    "Attack Path": "攻击路径",
    "Kill Chain": "杀伤链",
    "MITRE ATT&CK": "MITRE ATT&CK",
    "OWASP Top 10": "OWASP Top 10",
    "ISO 27001": "ISO 27001",
    "SOC 2": "SOC 2",
    "PCI DSS": "PCI DSS",
    "HIPAA": "HIPAA",
    "GDPR": "GDPR",
    "CCPA": "CCPA",
    "Infrastructure as Code": "基础设施即代码",
    "Secret Management": "密钥管理",
    "Certificate Management": "证书管理",
    "Event Bus": "事件总线",
    "Event Stream": "事件流",
    "Real-time Processing": "实时处理",
    "Batch Processing": "批量处理",
    "Stream Processing": "流处理",
    "Data Governance": "数据治理",
    "Data Security": "数据安全",
    "Data Privacy": "数据隐私",
    "Data Compliance": "数据合规",
    "DevOps": "DevOps",
    "Platform Engineering": "平台工程",
    "Site Reliability Engineering": "站点可靠性工程",
    "System Architecture": "系统架构",
    "Software Engineering": "软件工程",
    "Data Engineering": "数据工程",
    "ML Engineering": "ML 工程",
    "AI Engineering": "AI 工程",
    "Cybersecurity": "网络安全",
    "Cloud Engineering": "云工程",
    "Index Strategy": "索引策略",
    "Caching Strategy": "缓存策略",
    "Best Practices": "最佳实践",
    "System Design": "系统设计",
    "User Journey": "用户旅程",
    "Data Privacy": "数据隐私",
    "Load Testing": "负载测试",
    "Next Steps": "后续步骤",
    "Concrete Examples": "具体示例",
    "Output Format": "输出格式",
    "Industry Standards": "行业标准",
    "Mission-critical": "关键任务的",
    "Deliverable Templates": "交付物模板",
    "Database Architecture": "数据库架构",
    "Prioritization": "优先级排序",
    "Deep Expertise": "深厚专长",
    "Workflow Integration": "工作流程集成",
    "Throughout the Conversation": "整个对话中",
    "Remember and Build Upon": "记住并建立在以下基础上",
    "Remember and Accumulate Expertise": "记住并积累专业知识",
    "Battle-tested": "经过实战验证的",
    "Context Size": "上下文大小",
    "Context Window": "上下文窗口",
    "Context": "上下文",
    "Named Entity Recognition": "命名实体识别",
    "Retrieval-Augmented Generation": "检索增强生成",
    "Load Balancer": "负载均衡器",
    "Data-driven": "数据驱动的",
    "Uptime": "正常运行时间",
    "End-to-End Testing": "端到端测试",
    "Microservices Architecture": "微服务架构",
    "Event-driven": "事件驱动的",
    "Multi-factor Authentication": "多因素认证",
    "Screen Reader": "屏幕阅读器",
    "Computer Vision": "计算机视觉",
    "Database Optimization": "数据库优化",
    "Two-site Three-center": "两地三中心",
    "Same-city Dual-active": "同城双活",
    "Shadow Testing": "影子测试",
    "Post-mortem": "事后复盘",
    "Root Cause Analysis": "根因分析",
    "SM Algorithm": "国密算法",
    "Parameterized Query": "参数化查询",
    "WeChat Pay": "微信支付",
    "Regression Testing": "回归测试",
    "Defense in Depth": "纵深防御",
    "Horizontal Scaling": "水平扩展",
    "Mobile-first": "移动优先",
    "Visual Design": "视觉设计",
    "Model Serving": "模型服务",
    "Model Testing": "模型测试",
    "Knowledge Management": "知识管理",
    "Change Management": "变革管理",
}

def translate_line(line):
    """Translate a single line of English prose to Chinese."""
    if not line.strip():
        return line
    stripped = line.strip()
    
    # Skip formatting lines
    if stripped in ("---", "", "* * *", "--- --- ---"):
        return line
    
    # Skip code-like lines
    code_indicators = ["import ", "export ", "from ", "return ", "function ", "class ", 
                       "const ", "let ", "var ", "def ", "if (", "for (", "while (",
                       "self.", "this.", "$(", "#[", "//", "/*", "*/", "=>", "::",
                       "get ", "set ", "public ", "private ", "protected ", "static ",
                       "new ", "super ", "import(", "export(", "module", "require("]
    if any(indicator in stripped for indicator in code_indicators):
        return line
    
    # Skip pure identifiers
    if re.match(r'^[a-zA-Z_$][a-zA-Z0-9_$]*$', stripped):
        return line
    
    # Skip file paths, URLs, etc.
    if re.match(r'^(\.|/~|[a-z]:\\|https?://|git@|npm |pip |docker |kubectl |terraform )', stripped):
        return line
    
    # Skip table rows
    if stripped.startswith("|") and stripped.endswith("|"):
        return line
    
    # Skip lines with very little English
    english_words = re.findall(r'[A-Za-z]{3,}', stripped)
    if len(english_words) < 1:
        return line
    
    # Check if already has Chinese
    if any("\u4e00" <= c <= "\u9fff" for c in stripped):
        return line
    
    result = stripped
    
    # Apply header translations (longer first)
    for phrase, cn in sorted(HEADER_TRANS.items(), key=lambda x: -len(x[0])):
        if phrase in result:
            result = result.replace(phrase, cn)
    
    # Apply word translations (longer first)
    for en, cn in sorted(WORD_TRANS.items(), key=lambda x: -len(x[0])):
        result = result.replace(en, cn)
    
    # If the line is now mostly Chinese, keep it
    chinese_chars = sum(1 for c in result if "\u4e00" <= c <= "\u9fff")
    english_chars = len(re.findall(r'[A-Za-z]{3,}', result))
    
    if chinese_chars > 0 and (chinese_chars >= english_chars * 2 or english_chars <= 2):
        return result
    
    # If still mostly English, keep original
    if english_chars > chinese_chars * 2:
        return line
    
    return result

def process_file(filepath):
    """Process a single markdown file."""
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    
    lines = content.split("\n")
    result = []
    in_yaml = False
    in_code = False
    yaml_count = 0
    
    for line in lines:
        stripped = line.strip()
        
        # Toggle YAML frontmatter
        if stripped == "---":
            yaml_count += 1
            if yaml_count == 1:
                in_yaml = True
                result.append(line)
                continue
            elif yaml_count == 2:
                in_yaml = False
                yaml_count = 0
                result.append(line)
                continue
        
        # Toggle code blocks
        if stripped.startswith("```"):
            in_code = not in_code
            result.append(line)
            continue
        
        # Skip YAML and code blocks
        if in_yaml or in_code:
            result.append(line)
            continue
        
        # Translate prose line
        translated = translate_line(line)
        result.append(translated)
    
    return "\n".join(result)

def main():
    target_dirs = sys.argv[1:] if len(sys.argv) > 1 else []
    
    if not target_dirs:
        # List all directories with markdown files
        for d in sorted(os.listdir(BASE)):
            dirpath = os.path.join(BASE, d)
            if os.path.isdir(dirpath) and not d.startswith("."):
                md_files = [f for f in os.listdir(dirpath) if f.endswith(".md")]
                if md_files:
                    print(f"  {d}: {len(md_files)} files")
        return
    
    for dir_name in target_dirs:
        dirpath = os.path.join(BASE, dir_name)
        if not os.path.isdir(dirpath):
            print(f"Directory not found: {dir_name}")
            continue
        
        files = sorted([f for f in os.listdir(dirpath) if f.endswith(".md")])
        print(f"Processing {dir_name}: {len(files)} files...")
        
        for fpath in files:
            filepath = os.path.join(dirpath, fpath)
            try:
                new_content = process_file(filepath)
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(new_content)
            except Exception as e:
                print(f"  ERROR {fpath}: {e}")
        
        print(f"Done: {dir_name}")

if __name__ == "__main__":
    main()
